### ISSUE TITLE
joint_states

### ISSUE THREAD

**Issue by yiyongrobotics** [Parker-Zhang/Dynamxiel_Template-Tutorials#1]
Hi,

thanks for your work and sharing, now I am using this motor with ros based on some examples provided by DYNAMIXEL. and I found the ros topic joint_state cant update (it means no any change) even if this topic published when the motor is moving. could you please provide your WeChat so that I can contact you and discuss it?

kind regards,
YIYONG

**Comment by Parker-Zhang** [comment]
Hi, 
I'm sorry that I didn't reply you in time. I hope you have solved your problem.

> Hi,
> 
> thanks for your work and sharing, now I am using this motor with ros based on some examples provided by DYNAMIXEL. and I found the ros topic joint_state cant update (it means no any change) even if this topic published when the motor is moving. could you please provide your WeChat so that I can contact you and discuss it?
> 
> kind regards,
> YIYONG
